// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb0aHWMlPtdpge7vO3YUwsF1yBY4ma5lk',
    appId: '1:410489266470:web:290283de05d8188db9a1e7',
    messagingSenderId: '410489266470',
    projectId: 'notes-app-c0c77',
    authDomain: 'notes-app-c0c77.firebaseapp.com',
    storageBucket: 'notes-app-c0c77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb5_uj3adQ9MYdtrWZejSF2RjIhK4HYNw',
    appId: '1:410489266470:android:99745e471646a9eeb9a1e7',
    messagingSenderId: '410489266470',
    projectId: 'notes-app-c0c77',
    storageBucket: 'notes-app-c0c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY3x9kI-WGxwvyZKsceRFH1xnN_HeU7rE',
    appId: '1:410489266470:ios:f0620db05aa1e4a4b9a1e7',
    messagingSenderId: '410489266470',
    projectId: 'notes-app-c0c77',
    storageBucket: 'notes-app-c0c77.firebasestorage.app',
    iosBundleId: 'com.example.notepadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY3x9kI-WGxwvyZKsceRFH1xnN_HeU7rE',
    appId: '1:410489266470:ios:f0620db05aa1e4a4b9a1e7',
    messagingSenderId: '410489266470',
    projectId: 'notes-app-c0c77',
    storageBucket: 'notes-app-c0c77.firebasestorage.app',
    iosBundleId: 'com.example.notepadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb0aHWMlPtdpge7vO3YUwsF1yBY4ma5lk',
    appId: '1:410489266470:web:9ea683a9077c785cb9a1e7',
    messagingSenderId: '410489266470',
    projectId: 'notes-app-c0c77',
    authDomain: 'notes-app-c0c77.firebaseapp.com',
    storageBucket: 'notes-app-c0c77.firebasestorage.app',
  );
}
